### PR TITLE
[Sonic Generations] Upload 'Disable Invincibility Music' patch

### PR DESCRIPTION
**Pull request by hyperbx**
I'm sorry for ruining this, but it's worth it, trust me.

image

### CODE REVIEW

**Comment by RagdollClash** [comment]
forever staying open

**Comment by thesupersonic16** [comment]
image

**Comment by Sajidur78** [comment]
> but it's worth it, trust me.

Is it really?

**Comment by hyperbx** [comment]
yes

iizuka

**Review by Sajidur78 — APPROVED** [review]

**Comment by Sajidur78** [comment]
You've convinced me, LGTM.

**Comment by RagdollClash** [comment]
WOW

**Comment by thesupersonic16** [comment]
smh

**Comment by Sajidur78** [comment]
@ActualMandM @thesupersonic16 He put up a good argument.

**Comment by RagdollClash** [comment]
**IIZUKA ISN'T AN ARGUMENT**

**Review by RagdollClash — COMMENTED** [review]
I see now.

**Pull request merged**
