### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by ricky-daniel13**
Added Spanish localization

### CODE REVIEW

**Review by thesupersonic16 — CHANGES_REQUESTED** [review]
Before I can merge this I will need you to include `es-MX.xaml` into the `HedgeModManager` project so the file will be included in the exe. HMM will crash if you don't do this.

**Review by thesupersonic16 — CHANGES_REQUESTED** [review]
So I have had the translation checked. And we have some possible issues that we need you to check and fix.

The following are the lines that has gotten our attention:
- L33: Meaning is too far from "Supports Save"
- L43: Not translated? Ignore if "Name" is proper.
- L54: Like L33, the meaning for enabling save redirection is too far
- L60-L66: Not translated?
- L72: "Doing" may not be the right word for this. Should mean something like Create

**Comment by ricky-daniel13** [comment]
Hi, I did the changes you requested. However I dont think I understand what you meant with "you to include es-MX.xaml into the HedgeModManager"
It should be already in the folder; Unless you mean I need to add the file somewhere else, too

**Comment by ricky-daniel13** [comment]
I modified the save redirection strings but still using the word "Partida" which is a common term for game save files in spanish. However I can use the more literal "Archivo de Guardado" if you want

**Comment by thesupersonic16** [comment]
We had it checked again and there still seems to be some issues. These are the suggestions I was given. Let me know if any of these is wrong or inappropriate.
```
L33: Soporta Partida separada > Soporta Guardar
L54: Activar redireccion a partida separada > Activar la redirección de guardar archivo
L61: Obtener Actualizaciones del cargador de mdos > Obtener Actualizaciones del cargador de mod
L62: Obtener actualizacion del cargador de codigos > Obtener actualizacions del cargador de codigos
L65: About Hedge Mod Manager > Acerca de Hedge Mod Manager
```

As for the including `es-MX.xaml` Right click the file in the solution explorer and click `Include in Project`
image
If you do not have VS, please let me know so I can do it in a separate commit.

**Comment by ricky-daniel13** [comment]
Yeah those suggestions are fine. I dont have vs, i did the changes from github itself, sorry

**Comment by thesupersonic16** [comment]
Here is what I will do, Since most of the translation seems to be alright, I will merge your PR and have someone else fix up the minor detail. 

Thanks!

**Pull request merged**
