### PR TITLE
Updated pt-PT translation and added pt-BR

### PR DESCRIPTION
**Pull request by PTKay**
Fixed a typo in pt-PT, and made the about string smaller. Hopefully it'll fit in the window's space this time.
Also include is the pt-BR translation, which is based on the pt-PT one, but has some changes to suit the different language

### CODE REVIEW

**Comment by thesupersonic16** [comment]
Before I can merge this, I will need you to register `pt-BR` in [SetupLanguages()](https://github.com/thesupersonic16/HedgeModManager/blob/rewrite/HedgeModManager/App.xaml.cs#L238)

**Comment by PTKay** [comment]
Should be good I think

**Comment by thesupersonic16** [comment]
You will also need to add `pt-BR.xaml` to the project so it will be included in the exe.

**Comment by thesupersonic16** [comment]
LGTM

**Pull request merged**
