### PR TITLE
Korean(한국어) translation

### PR DESCRIPTION
**Pull request by teabarley**
what's 'made on'? anyway, 99.999% done.

### CODE REVIEW

**Comment by hyperbx** [comment]
The `ModDescriptionUIMadeOn` string is used in the mod info window for mods that have a creation date, but no author.

image

**Comment by teabarley** [comment]
Thank you!

**Comment by HyperBE32** [comment]
Just to confirm, is this ready to be merged?

**Comment by hyperbx** [comment]
Please add the following entry to `Languages.xaml`;
```
<local:LangEntry FileName="ko-KR" Name="한국어 (Korean)"/>
```

**Pull request merged**
