### PR TITLE
Replace AppVeyor with GitHub Actions

### PR DESCRIPTION
**Pull request by RagdollClash**
This PR adds a workflow that allows HedgeModManager to be built via GitHub Actions. It also uploads the compiled version as an 
artifact, so people can still download the latest compile.

### CODE REVIEW

**Comment by RagdollClash** [comment]
You can also use nightly.link to directly link to the artifact, as an example with this PR:
https://nightly.link/ActualMandM/HedgeModManager/workflows/build/actions/HedgeModManager-Release.zip

If this is merged, the artifact download for this repo *should* be
https://nightly.link/thesupersonic16/HedgeModManager/workflows/build/master/HedgeModManager-Release.zip

This has been reflected in the README.

**Comment by RagdollClash** [comment]
Debug builds are now generated, just like what AppVeyor does.

**Comment by thesupersonic16** [comment]
LGTM

**Comment by RagdollClash** [comment]
rest in pieces appveyor

**Pull request merged**
