### PR TITLE
Experimental 4:3

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by RagdollClash** [comment]
Can you post screenshots of how this looks in-game?

**Comment by Muzzarino** [comment]
There was one modification that I forgot to add earlier to make all HUD elements correspond to the XNCP interface params, and the 4:3 mode HUD's borked on positioning, just an FYI.

SonicGenerations 2021-11-01 12-54-29-722
SonicGenerations 2021-11-01 12-55-00-194
SonicGenerations 2021-11-01 12-55-17-046
SonicGenerations 2021-11-01 12-55-54-085

**Comment by RagdollClash** [comment]
I don't think it's mergeable in its current state if the in-game HUD is gonna be looking as broken as the images you sent...

**Comment by Muzzarino** [comment]
> I don't think it's mergeable in its current state if the in-game HUD is gonna be looking as broken as the images you sent...

That's how Generations programmed the HUD scaling behavior, where elements end up being squished instead of a proper left and right group like Colors (horizontal only).

**Comment by thesupersonic16** [comment]
I have discussed this mod with some people and have come with the conclusion that we are not going to merge this PR.

As this code requires modifications to files like xncp, we think it is better to just distribute this code as a separate mod with the modified files instead of it being a global code which will cause a broken HUD.

**Pull request closed without merging**
