### PR TITLE
Fix Sonic Colors Ultimate ExecutableName

### LINKED ISSUE #873: Sonic Colors Not Being Saved as Last Game
The mod manager kept defaulting to Sonic Generations on startup, so I did some debugging and found this:
https://github.com/thesupersonic16/HedgeModManager/blob/f071e0bfcbad78e31ecf2cdb07aa0b13ff92dacc/HedgeModManager/Game.cs#L104

At least on Steam, my executable is `SonicColorsUltimate.exe`. I've deleted the file and verified the game's integrity through Steam, so `SonicColorsUltimate.exe` is correct. Debugging with that line changed resulted in the mod manager selecting Sonic Colors on startup as expected.

### PR DESCRIPTION
**Pull request by TBirdSoars**
fixes #873

### CODE REVIEW

**Comment by RagdollClash** [comment]
Wouldn't this cause the issue to happen for EGS users instead?

**Comment by TBirdSoars** [comment]
I was not aware the executable was actually named differently between the stores. I only have it on Steam, so I can't test if this would impact EGS users. That would definitely make this more complicated.

**Comment by DeaTh-G** [comment]
The executable name on the EGS version is indeed name differently and is using the name that is already present in HMM.

**Comment by thesupersonic16** [comment]
Looks like an oversight while trying to get the Steam version added. The solution will need to include checking the path instead of the exe name.

I believe we would only need to update `FindAndSetLocalGame` in `HedgeApp.xaml.cs`. 

EDIT: 
Maybe you can just get the filename from `GamePath`/`GamePathEGS`. The game install searching works by sending back the directory that contains the exe.
Maybe even `GameInstall.SearchForGames` aswell for `ExtraGameDirectories`.

**Comment by TBirdSoars** [comment]
> Looks like an oversight while trying to get the Steam version added. The solution will need to include checking the path instead of the exe name.
> 
> I believe we would only need to update `FindAndSetLocalGame` in `HedgeApp.xaml.cs`.
> 
> EDIT: Maybe you can just get the filename from `GamePath`/`GamePathEGS`. The game install searching works by sending back the directory that contains the exe. Maybe even `GameInstall.SearchForGames` aswell for `ExtraGameDirectories`.

I've tried to implement that `GamePath` fix in dae9236e723ed7bf41ffd775ab9b3261f0c7bc7e, replacing every seemingly relevant `ExecutableName` with a check for  `GamePath`/`GamePathEGS`. While this did fix my issue with the Steam version, I'm still encountering a similar issue with the EGS version now that I have it to test.

I've also tried a different approach by adding the EGS version as its own `Game` with 2025ee8c2a90cc2c4db5dbbd04dac6ddaf5e314f. This appeared to fix my issue and avoids having so many extra checks for the `GamePath`/`GamePathEGS`, but resulted in the combo box having two entries named "Sonic Colors: Ultimate", without the launcher names included. Modifying the duplicate checking to use `GameName` instead of `BaseGame` seems to have corrected this.

I'm not sure which approach is necessarily better.

**Comment by thesupersonic16** [comment]
I currently have an uncommitted change that might help with this issue. May ask in here once I push it.

**Pull request closed without merging**
