### PR TITLE
Updated Spanish Translation

### PR DESCRIPTION
**Pull request by ricky-daniel13**
Added missing strings

### CODE REVIEW

**Review by thesupersonic16 — CHANGES_REQUESTED** [review]
Can you please preserve all the comments, order and spacing? This should be an easy fix by loading the language file into Hedge Mod Manager then pressing Shift + F4. Doing this will also override your language file.

**Comment by ricky-daniel13** [comment]
will do as soon as I can. Apologies.

**Comment by ricky-daniel13** [comment]
Sorry if "as soon as I can" took so long. I believe everything should be okay now. All strings translated by Febraury 1th, 2024

**Comment by ricky-daniel13** [comment]
All strings as of November 22th 2024 should be translated. Is there anything else wrong preventing this from being accepted?

**Pull request merged**
