### PR TITLE
Change SCU Icon to Match Executable

### PR DESCRIPTION
**Pull request by Sonen10**
(do not use my readme.md, use the one in the current branch)

### CODE REVIEW

**Review by thesupersonic16 — CHANGES_REQUESTED** [review]
I will have to discuss with some others if the icon should be changed, but I cannot accept this PR regardless until you revert the readme file.

**Comment by Sonen10** [comment]
Sorted that out!

**Review by thesupersonic16 — APPROVED** [review]
LGTM

**Review by Sajidur78 — APPROVED** [review]
LGTM

**Pull request merged**
