### PR TITLE
New LW shens

### PR DESCRIPTION
**Pull request by Muzzarino**

### CODE REVIEW

**Comment by Sajidur78** [comment]
Hey, the dynamic resolution code seems to work fine. But, the "Invisible cloak sonic" doesn't seem to do anything, did you forget to include the base address?

**Comment by Muzzarino** [comment]
> Hey, the dynamic resolution code seems to work fine. But, the "Invisible cloak sonic" doesn't seem to do anything, did you forget to include the base address?

To activate that cloak everytime you enter a stage, you'll need to jump or spin dash.

**Comment by Sajidur78** [comment]
The address seems to be wrong, changing it to 0x0085C68E seems to work.

**Comment by Muzzarino** [comment]
Updated

**Comment by Sajidur78** [comment]
LGTM

**Pull request merged**
