### PR TITLE
[Sonic Colours: Ultimate] Some codes that kill Tails

### PR DESCRIPTION
**Pull request by hyperbx**
- Disable Tails Save - stops Tails from saving you when falling to your death.
- Disable Hint Rings - removes the hint ring objects when you have the navigator on.

### CODE REVIEW

**Review by Sajidur78 — APPROVED** [review]
LGTM

**Review by RagdollClash — APPROVED** [review]
LGTM

**Comment by RagdollClash** [comment]
THE FIRST EVER DOUBLE LGTM

**Comment by Sajidur78** [comment]
He's too good

**Pull request merged**
